"""Shared utilities for platform adapters.

Internal module — not part of the public API. Subject to change without notice.
"""
from __future__ import annotations

import json
import shutil
import sys
import sysconfig
from pathlib import Path

# Legacy command patterns generated by v1.x _build_hooks functions.
# Used for backward-compatible uninstall of pre-v2 hooks.
_AGENTLINT_CMD_PATTERNS: tuple[str, ...] = (
    "agentlint check --event ",
    "agentlint report",
)


def resolve_command() -> str:
    """Resolve the absolute command to invoke agentlint.

    Probes multiple well-known locations in order:
    1. shutil.which() — PATH lookup
    2. ~/.local/bin/agentlint — pipx location
    3. ~/.local/share/uv/tools/agentlint/bin/agentlint — uv tool location
    4. sysconfig scripts dir — where pip puts console_scripts
    5. sys.executable -m agentlint — guaranteed to work with __main__.py
    """
    found = shutil.which("agentlint")
    if found:
        return found

    pipx = Path.home() / ".local" / "bin" / "agentlint"
    if pipx.is_file():
        return str(pipx)

    uv_tool = Path.home() / ".local" / "share" / "uv" / "tools" / "agentlint" / "bin" / "agentlint"
    if uv_tool.is_file():
        return str(uv_tool)

    scripts_dir = sysconfig.get_path("scripts")
    if scripts_dir:
        scripts_bin = Path(scripts_dir) / "agentlint"
        if scripts_bin.is_file():
            return str(scripts_bin)

    return f"{sys.executable} -m agentlint"


def read_json_config(path: Path) -> dict | None:
    """Read and parse a JSON config file.

    Returns {} if the file is missing, None if it is corrupted.
    """
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def write_json_config(path: Path, data: dict) -> None:
    """Write a JSON config file with indent=2. Creates parent dirs if needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def is_agentlint_nested_entry(entry: dict) -> bool:
    """Return True if a nested hook entry was installed by agentlint.

    Matches entries shaped like ``{"matcher": "...", "hooks": [{"type": "command", ...}]}``.
    """
    for hook in entry.get("hooks", []):
        if hook.get("_agentlint") == "v2":
            return True
        cmd = hook.get("command", "")
        if any(pat in cmd for pat in _AGENTLINT_CMD_PATTERNS):
            return True
    return False


def is_agentlint_flat_entry(entry: dict) -> bool:
    """Return True if a flat hook entry was installed by agentlint.

    Matches entries shaped like ``{"command": "...", "timeout": 5}``.
    """
    if entry.get("_agentlint") == "v2":
        return True
    cmd = entry.get("command", "")
    return any(pat in cmd for pat in _AGENTLINT_CMD_PATTERNS)
